apiVersion: v1
kind: Service
metadata: 
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
    role: logstor
  clusterIP: 10.96.99.99
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30080
 
