apiVersion: v1
kind: Pod
metadata: 
  name: poststart-pod
  namespace: default
spec:
  containers:
  - name: busybox-httpd
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command: ['mkdir','-p','/data/web/html'] 
    command: ["/bin/sh","-c","sleep 3600"]
    args: ["-f","-h /tmp/"]
