apiVersion: v1
kind: Service
metadata: 
  name: redis
  namespace: default
spec:
  selector:
    app: redis
    role: logstor
  clusterIP: 10.96.96.96
  type: ClusterIP
  ports: 
  - port: 6379
    targetPort: 6379
 
