apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  namespace: default
  
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        release: canary
        environment: qa
    spec:
      containers:
      - name: myapp-container
        image: dockerptu/httpd:v0.3
        ports: 
        - name: http
          containerPort: 80
